 ---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "chart.fullname" . }}
  labels:
    app:  {{ include "chart.fullname" . }}
  annotations:
    reloader.stakater.com/match: "true"
data:
  service.conf: |-
    location /{{ include "chart.fullname" . }} {
        proxy_pass http://{{ include "chart.fullname" . }}:{{ .Values.service.port }};
        include /usr/local/openresty/nginx/conf/proxy.conf;
    }