apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
        reloader.stakater.com/auto: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PLAYGROUND_PUBLIC_DOMAIN
              value: "{{ .Values.app.host }}"
            - name: PLAYGROUND_PUBLIC_DOMAIN_LOCAL_SSL_GENERATION
              value: "{{ .Values.app.generate_ssl_certs }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: "{{ .Values.app.scheme | upper  }}"
              httpHeaders:
                - name: Host
                  value: "{{ .Values.app.host }}"
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: "{{ .Values.app.scheme | upper }}"
              httpHeaders:
                - name: Host
                  value: "{{ .Values.app.host }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      
          volumeMounts:
            - name: config
              mountPath: /usr/local/openresty/nginx/services
              readOnly: true
              # subPath: namespace-services.conf
      volumes:
        - name: config
          configMap:
            defaultMode: 0777
            name:  {{ include "chart.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
