apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
        reloader.stakater.com/auto: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      initContainers:
        - name: ngnixconfig
          image: alpine:3.17.1
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: 
            - -c
            - >-
              apk update && apk add curl;
              echo "{\"data\": {\"{{ include "chart.fullname" . }}\": \"$(cat /tmp/service.conf |sed 's/$/\\n/g')\"}}" > /tmp/patch.json;
              curl -skX PATCH https://kubernetes.default.svc/api/v1/namespaces/{{ .Release.Namespace }}/configmaps/openresty -H "Authorization: Bearer $( cat /var/run/secrets/kubernetes.io/serviceaccount/token )" -H "Content-Type: application/merge-patch+json; charset=utf-8" -d "@/tmp/patch.json"
          volumeMounts:
            - name: config
              mountPath: /tmp/service.conf
              readOnly: true
              subPath: service.conf
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            defaultMode: 0777
            name:  {{ include "chart.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
